on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          src_path: /.
          dst_path: /.
          dst_owner: portaler-zone
          dst_repo_name: portaler-core
          dst_branch: netlify
          clean: true
          exclude: '*/{api-server,discord-bot,bin-etl,data-models}/*'
